// <auto-generated />
using System;
using InvestmentTracker;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace InvestmentTracker.Migrations
{
    [DbContext(typeof(InvestmentdbContext))]
    [Migration("20200706221707_ChangingSet")]
    partial class ChangingSet
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("InvestmentTracker.Expenditure", b =>
                {
                    b.Property<int>("ExpenditureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Day")
                        .HasColumnType("datetime2");

                    b.Property<float>("ExpenseAmount")
                        .HasColumnType("real");

                    b.Property<int>("PeopleId")
                        .HasColumnType("int");

                    b.Property<string>("PurposeOfExpenditure")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ExpenditureId");

                    b.HasIndex("PeopleId");

                    b.ToTable("Expenditures");
                });

            modelBuilder.Entity("InvestmentTracker.Income", b =>
                {
                    b.Property<int>("IncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Day")
                        .HasColumnType("datetime2");

                    b.Property<float>("IncomeReceived")
                        .HasColumnType("real");

                    b.Property<int>("PeopleId")
                        .HasColumnType("int");

                    b.Property<string>("SourceOfIncome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IncomeId");

                    b.HasIndex("PeopleId");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("InvestmentTracker.People", b =>
                {
                    b.Property<int>("PeopleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PeopleId");

                    b.ToTable("Peoples");
                });

            modelBuilder.Entity("InvestmentTracker.Expenditure", b =>
                {
                    b.HasOne("InvestmentTracker.People", "People")
                        .WithMany("Expenditures")
                        .HasForeignKey("PeopleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("InvestmentTracker.Income", b =>
                {
                    b.HasOne("InvestmentTracker.People", "People")
                        .WithMany("Incomes")
                        .HasForeignKey("PeopleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
